# Site Settings
title: TWDC | Apple Authorized Training Provider
email: service@twdc.tw
description: Some text about your blog.
url: "https://twdc.blog" 
#google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: TWDC
user_description: 
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
facebook_username: TaichungAATP


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Tags
    url: /tags/


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
